
loading weights from pretrained gpt: gpt2
found 99 shards for split train
found 1 shards for split val
num decayed parameter tensors: 5, with 192,986,880 parameters
num non-decayed parameter tensors: 10, with 7,680 parameters
using fused AdamW: True
validation loss: 5.4144
Traceback (most recent call last):
  File "/data/my_scripts/interesting_toy_exp/multiple_generation_head/train_multiple_softmax.py", line 166, in <module>
    output_list = raw_model.generate(input_ids, max_new_tokens, do_sample=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangxiaobo/miniconda3/envs/test/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/my_scripts/interesting_toy_exp/multiple_generation_head/models/model_gpt2_multi_sofmax.py", line 95, in generate
    inter_logits, _ = self(idx_cond)
                      ^^^^^^^^^^^^^^
  File "/home/yangxiaobo/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yangxiaobo/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/my_scripts/interesting_toy_exp/multiple_generation_head/models/model_gpt2_multi_sofmax.py", line 86, in forward
    return inter_logits, loss, losses
                               ^^^^^^
UnboundLocalError: cannot access local variable 'losses' where it is not associated with a value
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/my_scripts/interesting_toy_exp/multiple_generation_head/train_multiple_softmax.py", line 166, in <module>
[rank0]:     output_list = raw_model.generate(input_ids, max_new_tokens, do_sample=False)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/yangxiaobo/miniconda3/envs/test/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/data/my_scripts/interesting_toy_exp/multiple_generation_head/models/model_gpt2_multi_sofmax.py", line 95, in generate
[rank0]:     inter_logits, _ = self(idx_cond)
[rank0]:                       ^^^^^^^^^^^^^^
[rank0]:   File "/home/yangxiaobo/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/yangxiaobo/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/data/my_scripts/interesting_toy_exp/multiple_generation_head/models/model_gpt2_multi_sofmax.py", line 86, in forward
[rank0]:     return inter_logits, loss, losses
[rank0]:                                ^^^^^^
[rank0]: UnboundLocalError: cannot access local variable 'losses' where it is not associated with a value